version: "3.8"
services:
  redis:
    image: redis
    container_name: bppc-redis
    restart: always
  console:
    container_name: bppc-console
    restart: always
    build:
      context: .
      dockerfile: ./docker/console/Dockerfile
    volumes:
      - .:/opt/bppc
    depends_on:
      - redis
  api:
    container_name: bppc-api
    restart: always
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - .:/opt/bppc
    ports:
      - 8000:8000
    depends_on:
      - console
      - redis
