version: "3.8"
services:
  api:
    container_name: bunnycdn-purge-perma-cache
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
